In [9]:

import pandas as pd

OUTPUT_PATH = f"../../Datasets/Evaluations/Schema Matching/logistic_regression.csv"
TEST_CORRESPONDENCES_PATH = "../../Datasets/t2d_sm_nh/test/test_correspondences_sample_logistic.csv"
TRAIN_CORRESPONDENCES_PATH = "../../Datasets/t2d_sm_nh/train/train_correspondences_sample.csv"

In [10]:
# Read the CSV file into a DataFrame
df_test = pd.read_csv(TEST_CORRESPONDENCES_PATH)
df_train = pd.read_csv(TRAIN_CORRESPONDENCES_PATH)

df_test = df_test.drop("prompt", axis=1)
df_test = df_test.drop("prompt_name", axis=1)
df_train = df_train.drop("prompt", axis=1)
df_train = df_train.drop("prompt_name", axis=1)

#print(df_test.head())
print(df_train.head())

   table_index                      table_name  column_index_left  \
0            0  57938705_0_8737506792349461963                  9
1            1  57938705_0_8737506792349461963                  3
2            2  57938705_0_8737506792349461963                  2
3            3  57938705_0_8737506792349461963                  1
4            4  57938705_0_8737506792349461963                  4

   column_index_right  y_true  y_pred  \
0                   0    True     NaN
1                   0   False     NaN
2                   0   False     NaN
3                   0   False     NaN
4                   0   False     NaN

                                      column_table_A  \
0  462.06 | Super Mario Land | Nintendogs | Wii F...
1         143.65 | 1989.0 | 2005.0 | 2009.0 | 2005.0
2  70.32 | Platform | Simulation | Sports | Simul...
3                        256.81 | GB | DS | Wii | DS
4  932.83 | Nintendo | Nintendo | Nintendo | Nint...

                                      column_table_B  \
0  Cafe Little Wish | PowerWash Simulator | Castl...
1  Cafe Little Wish | PowerWash Simulator | Castl...
2  Cafe Little Wish | PowerWash Simulator | Castl...
3  Cafe Little Wish | PowerWash Simulator | Castl...
4  Cafe Little Wish | PowerWash Simulator | Castl...

                                             table_A  \
0  | Column A-0   | Column A-1   | Column A-2   |...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

                                             table_B
0  | Column B-0                                  ...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

In [11]:
last = ""
table_A = ""
table_B = ""

for i in range(0, len(df_test)):
    if last != df_test["table_name"].iloc[i]:
        last = df_test["table_name"].iloc[i]
        table_A = df_test["table_A"].iloc[i]
        table_B = df_test["table_B"].iloc[i]
        print(i)
    else:
        df_test.loc[i, 'table_A'] = table_A
        df_test.loc[i, 'table_B'] = table_B

last = ""
table_A = ""
table_B = ""

for i in range(0, len(df_test)):
    if last != df_train["table_name"].iloc[i]:
        last = df_train["table_name"].iloc[i]
        table_A = df_train["table_A"].iloc[i]
        table_B = df_train["table_B"].iloc[i]
        print(i)
    else:
        df_train.loc[i, 'table_A'] = table_A
        df_train.loc[i, 'table_B'] = table_B

0
12
26
50
82
94
111
137
149
168
185
198
235
241
256
274
294
309
324
346
360
372
384
395
408
425
432
445
0
32
55
72
84
114
125
148
159
189
207
230
251
264
291
302
331
346
365
390
406
430
437

In [12]:
print(df_train['column_table_A'][14])
print(df_train['table_A'][12])

nan | 4.18 | 1.93 | 2.49 | 5.33
| Column A-0   | Column A-1   | Column A-2   |   Column A-3 | Column A-4   |   Column A-5 |   Column A-6 |   Column A-7 |   Column A-8 | Column A-9                  |   Column A-10 |
|:-------------|:-------------|:-------------|-------------:|:-------------|-------------:|-------------:|-------------:|-------------:|:----------------------------|--------------:|
| Total        | 256.81       | 70.32        |       143.65 | 932.83       |       nan    |       nan    |       nan    |       nan    | 462.06                      |        nan    |
| 19           | GB           | Platform     |      1989    | Nintendo     |         4.18 |        18.14 |        10.83 |         2.71 | Super Mario Land            |          0.42 |
| 10           | DS           | Simulation   |      2005    | Nintendo     |         1.93 |        24.37 |         9.01 |        10.71 | Nintendogs                  |          2.72 |
| 15           | Wii          | Sports       |      2009    | Nintendo     |         2.49 |        21.17 |         8.7  |         7.79 | Wii Fit Plus                |          2.2  |
| 34           | DS           | Simulation   |      2005    | Nintendo     |         5.33 |        11.74 |         2.42 |         3.17 | Animal Crossing: Wild World |          0.83 |

In [13]:
df_train['y_true'] = df_train['y_true'].replace(True, 1).replace(False, 0)
df_test['y_true'] = df_test['y_true'].replace(True, 1).replace(False, 0)
print(df_train['table_B'][1])

| Column B-0                                    | Column B-1             | Column B-2                                                                                  | Column B-3              | Column B-4             |
|:----------------------------------------------|:-----------------------|:--------------------------------------------------------------------------------------------|:------------------------|:-----------------------|
| Cafe Little Wish                              | 2003-02-14, 2003-05-29 | Dreamcast, PlayStation 2, Microsoft Windows                                                 | Visual novel, Eroge     | Princess Soft          |
| PowerWash Simulator                           | 2022-07-14             | Nintendo Switch, PlayStation 4, PlayStation 5, Microsoft Windows, Xbox One, Xbox Series X/S | Simulation game         | Square Enix Collective |
| Castlevania: Bloodlines                       | 1994-03-17             | Sega Genesis                                                                                | Platform game           | Konami                 |
| Cadillacs and Dinosaurs: The Second Cataclysm | nan                    | MS-DOS, Sega CD                                                                             | Rail shooter            | Sega                   |
| Power Blade 2                                 | nan                    | Nintendo Entertainment System                                                               | Platformer, Action game | Taito                  |

/var/folders/pw/9fnphybj4kq8t6wt3h592_9r0000gn/T/ipykernel_4358/2621829950.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train['y_true'] = df_train['y_true'].replace(True, 1).replace(False, 0)
/var/folders/pw/9fnphybj4kq8t6wt3h592_9r0000gn/T/ipykernel_4358/2621829950.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_test['y_true'] = df_test['y_true'].replace(True, 1).replace(False, 0)

In [14]:
df_train['tables_combined'] = df_train['table_A'] + " " + df_train['table_B']
df_test['tables_combined'] = df_test['table_A'] + " " + df_test['table_B']
df_train['tables_combined'] = df_train['tables_combined'].astype(str)
df_test['tables_combined'] = df_test['tables_combined'].astype(str)

df_train['table_A'] = df_train['table_A'].astype(str)
df_train['table_B'] = df_train['table_B'].astype(str)
df_test['table_A'] = df_test['table_A'].astype(str)
df_test['table_B'] = df_test['table_B'].astype(str)

In [15]:
#df_train['column_table_A'] = df_train['column_table_A'].str.replace('|', '')
#df_train['column_table_B'] = df_train['column_table_B'].str.replace('|', '')

#df_test['column_table_A'] = df_test['column_table_A'].str.replace('|', '')
#df_test['column_table_B'] = df_test['column_table_B'].str.replace('|', '')

In [54]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack
from sklearn.preprocessing import MaxAbsScaler
from sklearn.decomposition import TruncatedSVD

# Initialize the TF-IDF Vectorizer for each independent column
tfidf_vectorizer_A = TfidfVectorizer()
tfidf_vectorizer_B = TfidfVectorizer()
tfidf_vectorizer_table = TfidfVectorizer()

# Fit on the training data and transform both training and testing data for each column
tfidf_A_train = tfidf_vectorizer_A.fit_transform(df_train['column_table_A'])
tfidf_B_train = tfidf_vectorizer_B.fit_transform(df_train['column_table_B'])
tfidf_table_train = tfidf_vectorizer_table.fit_transform(df_train['tables_combined'])

tfidf_A_test = tfidf_vectorizer_A.transform(df_test['column_table_A'])
tfidf_B_test = tfidf_vectorizer_B.transform(df_test['column_table_B'])
tfidf_table_test = tfidf_vectorizer_table.transform(df_test['tables_combined'])

X_train = hstack([tfidf_A_train, tfidf_B_train, tfidf_table_train])
X_test = hstack([tfidf_A_test, tfidf_B_test, tfidf_table_test])


y_train = df_train['y_true']
y_test = df_test['y_true']

#took paramter values that made sence / roughly fitted on training data until it stopped only responding with false values
model = LogisticRegression(C=1, max_iter=1000, class_weight={0: 1, 1: 1.5})

model.fit(X_train, y_train)

y_pred_test = model.predict(X_test)

y_pred_train = model.predict(X_train)

accuracy_test = accuracy_score(y_test, y_pred_test)
conf_matrix_test = confusion_matrix(y_test, y_pred_test)
precision_test = precision_score(y_test, y_pred_test)
recall_test = recall_score(y_test, y_pred_test)
f1_test = f1_score(y_test, y_pred_test)


accuracy_train = accuracy_score(y_train, y_pred_train)
conf_matrix_train = confusion_matrix(y_train, y_pred_train)
precision_train = precision_score(y_train, y_pred_train)
recall_train = recall_score(y_train, y_pred_train)
f1_train = f1_score(y_train, y_pred_train)

print("Testing Set Results:")
print(f"Accuracy: {accuracy_test}")
print(f"Precision: {precision_test}")
print(f"Recall: {recall_test}")
print(f"F1 Score: {f1_test}")
print(f"Confusion Matrix:\n{conf_matrix_test}")

print("\nTraining Set Results:")
print(f"Accuracy: {accuracy_train}")
print(f"Precision: {precision_train}")
print(f"Recall: {recall_train}")
print(f"F1 Score: {f1_train}")
print(f"Confusion Matrix:\n{conf_matrix_train}")

df_test['y_pred'] = y_pred_test

Testing Set Results:
Accuracy: 0.45555555555555555
Precision: 0.183206106870229
Recall: 0.6075949367088608
F1 Score: 0.28152492668621704
Confusion Matrix:
[[157 214]
 [ 31  48]]

Training Set Results:
Accuracy: 0.8786729857819905
Precision: 1.0
Recall: 0.2768361581920904
F1 Score: 0.4336283185840708
Confusion Matrix:
[[878   0]
 [128  49]]

In [55]:
import numpy as np
# Combine feature names
feature_names = np.concatenate([
    tfidf_vectorizer_A.get_feature_names_out(),
    tfidf_vectorizer_B.get_feature_names_out()
])

# Extract coefficients
coefficients = model.coef_[0]

# Create a mapping from feature names to coefficients
feature_weights = dict(zip(feature_names, coefficients))

import re

def preprocess_text(text):
    # Lowercase
    text = text.lower()
    # Remove non-alphanumeric characters
    text = re.sub(r'\W+', ' ', text)
    # Return the preprocessed text
    return text

def get_token_weights(text, vectorizer, feature_weights):
    # Apply preprocessing to match the vectorizer's preprocessing
    preprocessed_text = preprocess_text(text)
    # Split the preprocessed text into tokens
    tokens = preprocessed_text.split()
    # Retrieve and format the weights for each token found in feature_weights
    weights_str = ", ".join([f"{token}: {feature_weights.get(token, 0):.4f}" for token in tokens if token in feature_weights])
    return weights_str

df_test['token_weights'] = df_test.apply(lambda row: get_token_weights(row['column_table_A'], tfidf_vectorizer_A, feature_weights) + ", " +
                                                      get_token_weights(row['column_table_B'], tfidf_vectorizer_B, feature_weights), axis=1)

In [56]:
for index, row in df_test.iterrows():
    print(f"column_table_A: {row['column_table_A']}")
    print(f"column_table_B: {row['column_table_B']}")
    print(f"token_weights: {row['token_weights']}")
    print()

column_table_A: Domitian | Nerva | Hadrian | Trajan | Titus
column_table_B: Trajan | Titus | Marcus Silius Messala | Vespasian | Nerva
token_weights: ,

column_table_A: Titus Flavius Domitianus | Marcus Cocceius Nerva | Publius Aelius Hadrianus | Marcus Ulpius Trajanus | Titus Flavius Sabinus Vespasianus
column_table_B: Trajan | Titus | Marcus Silius Messala | Vespasian | Nerva
token_weights: ,

column_table_A: 81-96 | 96-8 | 117-8 | 98-117 | 79-81
column_table_B: Trajan | Titus | Marcus Silius Messala | Vespasian | Nerva
token_weights: 81: -0.3303, 96: -0.5253, 96: -0.5253, 117: 0.1689, 98: 0.0950, 117: 0.1689, 79: -0.1511, 81: -0.3303,

column_table_A: nan | nan | nan | nan | nan
column_table_B: Trajan | Titus | Marcus Silius Messala | Vespasian | Nerva
token_weights: nan: 0.1721, nan: 0.1721, nan: 0.1721, nan: 0.1721, nan: 0.1721,

column_table_A: Domitian | Nerva | Hadrian | Trajan | Titus
column_table_B: Imperator Caesar Nerva Traianus Augustus | Imperator Titus Caesar Vespasianus Augustus | nan | Imperator Caesar Vespasianus Augustus | Imperator Nerva Caesar Augustus
token_weights: , caesar: -0.0357, caesar: -0.0357, nan: 0.1721, caesar: -0.0357, caesar: -0.0357

column_table_A: Titus Flavius Domitianus | Marcus Cocceius Nerva | Publius Aelius Hadrianus | Marcus Ulpius Trajanus | Titus Flavius Sabinus Vespasianus
column_table_B: Imperator Caesar Nerva Traianus Augustus | Imperator Titus Caesar Vespasianus Augustus | nan | Imperator Caesar Vespasianus Augustus | Imperator Nerva Caesar Augustus
token_weights: , caesar: -0.0357, caesar: -0.0357, nan: 0.1721, caesar: -0.0357, caesar: -0.0357

column_table_A: Domitian | Nerva | Hadrian | Trajan | Titus
column_table_B: nan | Titus Flavius Vespasianus, Titus Caesar Vespasianus | nan | Titus Flavius Vespasianus | nan
token_weights: , nan: 0.1721, caesar: -0.0357, nan: 0.1721, nan: 0.1721

column_table_A: Titus Flavius Domitianus | Marcus Cocceius Nerva | Publius Aelius Hadrianus | Marcus Ulpius Trajanus | Titus Flavius Sabinus Vespasianus
column_table_B: nan | Titus Flavius Vespasianus, Titus Caesar Vespasianus | nan | Titus Flavius Vespasianus | nan
token_weights: , nan: 0.1721, caesar: -0.0357, nan: 0.1721, nan: 0.1721

column_table_A: 81-96 | 96-8 | 117-8 | 98-117 | 79-81
column_table_B: nan | Titus Flavius Vespasianus, Titus Caesar Vespasianus | nan | Titus Flavius Vespasianus | nan
token_weights: 81: -0.3303, 96: -0.5253, 96: -0.5253, 117: 0.1689, 98: 0.0950, 117: 0.1689, 79: -0.1511, 81: -0.3303, nan: 0.1721, caesar: -0.0357, nan: 0.1721, nan: 0.1721

column_table_A: Titus Flavius Domitianus | Marcus Cocceius Nerva | Publius Aelius Hadrianus | Marcus Ulpius Trajanus | Titus Flavius Sabinus Vespasianus
column_table_B: 9811.0 | 1979.0 | nan | 1969.0 | 1996.0
token_weights: , 1979: -0.1365, nan: 0.1721, 1969: 0.2322, 1996: 0.2185

column_table_A: 81-96 | 96-8 | 117-8 | 98-117 | 79-81
column_table_B: 9811.0 | 1979.0 | nan | 1969.0 | 1996.0
token_weights: 81: -0.3303, 96: -0.5253, 96: -0.5253, 117: 0.1689, 98: 0.0950, 117: 0.1689, 79: -0.1511, 81: -0.3303, 1979: -0.1365, nan: 0.1721, 1969: 0.2322, 1996: 0.2185

column_table_A: nan | nan | nan | nan | nan
column_table_B: Hispania Baetica, Italica,  | Roman Italy, Rome | nan | Roman Italy, Falacrina | Roman Italy, Narni
token_weights: nan: 0.1721, nan: 0.1721, nan: 0.1721, nan: 0.1721, nan: 0.1721, italy: -0.0268, nan: 0.1721, italy: -0.0268, italy: -0.0268

column_table_A: Spain | Taiwan | Czech Republic | Venezuela | New Zealand
column_table_B: Bulgaria | Papua New Guinea | Sudan | Croatia | Aruba
token_weights: spain: 0.0332, taiwan: -0.0017, republic: -0.0464, venezuela: -0.0850, new: 0.3506, zealand: -0.0507, bulgaria: 0.0070, new: 0.3506, guinea: -0.0178, sudan: -0.2903, aruba: -0.0266

column_table_A: Peseta (ESP) | Dollar (TWD) | Koruna (CZK) | Bolivar (VEB) | Dollar (NZD)
column_table_B: Bulgaria | Papua New Guinea | Sudan | Croatia | Aruba
token_weights: dollar: -0.0515, dollar: -0.0515, bulgaria: 0.0070, new: 0.3506, guinea: -0.0178, sudan: -0.2903, aruba: -0.0266

column_table_A: 0.00675 | 0.02775 | 0.04714 | nan | 0.7849
column_table_B: Bulgaria | Papua New Guinea | Sudan | Croatia | Aruba
token_weights: nan: 0.1721, bulgaria: 0.0070, new: 0.3506, guinea: -0.0178, sudan: -0.2903, aruba: -0.0266

column_table_A: Spain | Taiwan | Czech Republic | Venezuela | New Zealand
column_table_B: nan | Related articles, UNESCO Science Report: towards 2030 | nan | nan | Geographic locale, International membership and history, Languages in Aruba, National origins, Religions of Aruba
token_weights: spain: 0.0332, taiwan: -0.0017, republic: -0.0464, venezuela: -0.0850, new: 0.3506, zealand: -0.0507, nan: 0.1721, science: -0.0190, nan: 0.1721, nan: 0.1721, international: -0.0169, and: -0.2904, history: 0.0406, languages: -0.0119, in: -0.3743, aruba: -0.0266, national: -0.0815, of: -0.4651, aruba: -0.0266

column_table_A: Peseta (ESP) | Dollar (TWD) | Koruna (CZK) | Bolivar (VEB) | Dollar (NZD)
column_table_B: nan | Related articles, UNESCO Science Report: towards 2030 | nan | nan | Geographic locale, International membership and history, Languages in Aruba, National origins, Religions of Aruba
token_weights: dollar: -0.0515, dollar: -0.0515, nan: 0.1721, science: -0.0190, nan: 0.1721, nan: 0.1721, international: -0.0169, and: -0.2904, history: 0.0406, languages: -0.0119, in: -0.3743, aruba: -0.0266, national: -0.0815, of: -0.4651, aruba: -0.0266

column_table_A: Spain | Taiwan | Czech Republic | Venezuela | New Zealand
column_table_B: National Assembly (Bulgaria) | National Parliament of Papua New Guinea | Transitional Legislative Council (Sudan) | Sabor | nan
token_weights: spain: 0.0332, taiwan: -0.0017, republic: -0.0464, venezuela: -0.0850, new: 0.3506, zealand: -0.0507, national: -0.0815, bulgaria: 0.0070, national: -0.0815, of: -0.4651, new: 0.3506, guinea: -0.0178, legislative: 0.0415, council: -0.0266, sudan: -0.2903, nan: 0.1721

column_table_A: Peseta (ESP) | Dollar (TWD) | Koruna (CZK) | Bolivar (VEB) | Dollar (NZD)
column_table_B: National Assembly (Bulgaria) | National Parliament of Papua New Guinea | Transitional Legislative Council (Sudan) | Sabor | nan
token_weights: dollar: -0.0515, dollar: -0.0515, national: -0.0815, bulgaria: 0.0070, national: -0.0815, of: -0.4651, new: 0.3506, guinea: -0.0178, legislative: 0.0415, council: -0.0266, sudan: -0.2903, nan: 0.1721

column_table_A: Refer to Euro | 0.03751 | 0.05870 | nan | 0.8866
column_table_B: National Assembly (Bulgaria) | National Parliament of Papua New Guinea | Transitional Legislative Council (Sudan) | Sabor | nan
token_weights: to: 0.2106, euro: -0.0440, nan: 0.1721, national: -0.0815, bulgaria: 0.0070, national: -0.0815, of: -0.4651, new: 0.3506, guinea: -0.0178, legislative: 0.0415, council: -0.0266, sudan: -0.2903, nan: 0.1721

column_table_A: Spain | Taiwan | Czech Republic | Venezuela | New Zealand
column_table_B: 8.6E10 | 2.1543E10 | 3.0808E10 | 6.938E10 | 3.4E9
token_weights: spain: 0.0332, taiwan: -0.0017, republic: -0.0464, venezuela: -0.0850, new: 0.3506, zealand: -0.0507, 0808e10: 0.2904

column_table_A: Refer to Euro | 0.03751 | 0.05870 | nan | 0.8866
column_table_B: 8.6E10 | 2.1543E10 | 3.0808E10 | 6.938E10 | 3.4E9
token_weights: to: 0.2106, euro: -0.0440, nan: 0.1721, 0808e10: 0.2904

column_table_A: Spain | Taiwan | Czech Republic | Venezuela | New Zealand
column_table_B: Bulgarian lev | Papua New Guinean kina | Sudanese pound | Croatian kuna | nan
token_weights: spain: 0.0332, taiwan: -0.0017, republic: -0.0464, venezuela: -0.0850, new: 0.3506, zealand: -0.0507, new: 0.3506, pound: -0.2555, nan: 0.1721

column_table_A: Peseta (ESP) | Dollar (TWD) | Koruna (CZK) | Bolivar (VEB) | Dollar (NZD)
column_table_B: Bulgarian lev | Papua New Guinean kina | Sudanese pound | Croatian kuna | nan
token_weights: dollar: -0.0515, dollar: -0.0515, new: 0.3506, pound: -0.2555, nan: 0.1721

column_table_A: 0.00675 | 0.02775 | 0.04714 | nan | 0.7849
column_table_B: Bulgarian lev | Papua New Guinean kina | Sudanese pound | Croatian kuna | nan
token_weights: nan: 0.1721, new: 0.3506, pound: -0.2555, nan: 0.1721

column_table_A: 0.00675 | 0.02775 | 0.04714 | nan | 0.7849
column_table_B: decrease | increase | increase | increase | nan
token_weights: nan: 0.1721, nan: 0.1721

column_table_A: Franc Congolais | Euro | Australian Dollar | New Zealand Dollar | Chilean Peso
column_table_B: Swiss franc | Czech koruna | Unidad de Fomento | Maltese scudo | Cambodian riel
token_weights: franc: -0.0706, euro: -0.0440, dollar: -0.0515, new: 0.3506, zealand: -0.0507, dollar: -0.0515, peso: -0.0706, swiss: -0.1443, franc: -0.0706, de: -0.1313

column_table_A: Congo, The Democratic Republic Of | French Southern Territories | Cocos (Keeling) Islands | Cook Islands | Chile
column_table_B: Swiss franc | Czech koruna | Unidad de Fomento | Maltese scudo | Cambodian riel
token_weights: the: -0.3987, republic: -0.0464, of: -0.4651, french: -0.0209, southern: 0.1342, cocos: -0.0532, keeling: -0.1678, islands: -0.1989, cook: 0.0286, islands: -0.1989, chile: -0.3666, swiss: -0.1443, franc: -0.0706, de: -0.1313

column_table_A: CDF | EUR | AUD | NZD | CLP
column_table_B: Swiss franc | Czech koruna | Unidad de Fomento | Maltese scudo | Cambodian riel
token_weights: eur: 0.2259, swiss: -0.1443, franc: -0.0706, de: -0.1313

column_table_A: 100 centimes | 100 euro-cents | 100 cents | 100 cents | 100 centavos
column_table_B: Swiss franc | Czech koruna | Unidad de Fomento | Maltese scudo | Cambodian riel
token_weights: 100: -0.0244, centimes: 0.1231, 100: -0.0244, euro: -0.0440, cents: -0.0713, 100: -0.0244, cents: -0.0713, 100: -0.0244, cents: -0.0713, 100: -0.0244, swiss: -0.1443, franc: -0.0706, de: -0.1313

column_table_A: nan |  | A$ | NZ$ | Ch$
column_table_B: Swiss franc | Czech koruna | Unidad de Fomento | Maltese scudo | Cambodian riel
token_weights: nan: 0.1721, swiss: -0.1443, franc: -0.0706, de: -0.1313

column_table_A: Franc Congolais | Euro | Australian Dollar | New Zealand Dollar | Chilean Peso
column_table_B: Schweizer Franken, franc suisse, franc svizzer, franco svizzero | koruna česká | nan | Scudo maltese, Skud Malti | រៀលកម្ពុជា/រៀលខ្មែរ
token_weights: franc: -0.0706, euro: -0.0440, dollar: -0.0515, new: 0.3506, zealand: -0.0507, dollar: -0.0515, peso: -0.0706, franc: -0.0706, franc: -0.0706, nan: 0.1721

column_table_A: nan |  | A$ | NZ$ | Ch$
column_table_B: Schweizer Franken, franc suisse, franc svizzer, franco svizzero | koruna česká | nan | Scudo maltese, Skud Malti | រៀលកម្ពុជា/រៀលខ្មែរ
token_weights: nan: 0.1721, franc: -0.0706, franc: -0.0706, nan: 0.1721

column_table_A: 976 | 978 | 36 | 554 | 152
column_table_B: Schweizer Franken, franc suisse, franc svizzer, franco svizzero | koruna česká | nan | Scudo maltese, Skud Malti | រៀលកម្ពុជា/រៀលខ្មែរ
token_weights: 978: -0.3476, 36: -0.2700, 554: -0.3463, franc: -0.0706, franc: -0.0706, nan: 0.1721

column_table_A: Franc Congolais | Euro | Australian Dollar | New Zealand Dollar | Chilean Peso
column_table_B: CHF | CZK | CLF | none | KHR
token_weights: franc: -0.0706, euro: -0.0440, dollar: -0.0515, new: 0.3506, zealand: -0.0507, dollar: -0.0515, peso: -0.0706, chf: 0.2843, none: 0.4273

column_table_A: Congo, The Democratic Republic Of | French Southern Territories | Cocos (Keeling) Islands | Cook Islands | Chile
column_table_B: CHF | CZK | CLF | none | KHR
token_weights: the: -0.3987, republic: -0.0464, of: -0.4651, french: -0.0209, southern: 0.1342, cocos: -0.0532, keeling: -0.1678, islands: -0.1989, cook: 0.0286, islands: -0.1989, chile: -0.3666, chf: 0.2843, none: 0.4273

column_table_A: CDF | EUR | AUD | NZD | CLP
column_table_B: CHF | CZK | CLF | none | KHR
token_weights: eur: 0.2259, chf: 0.2843, none: 0.4273

column_table_A: nan |  | A$ | NZ$ | Ch$
column_table_B: CHF | CZK | CLF | none | KHR
token_weights: nan: 0.1721, chf: 0.2843, none: 0.4273

column_table_A: 976 | 978 | 36 | 554 | 152
column_table_B: CHF | CZK | CLF | none | KHR
token_weights: 978: -0.3476, 36: -0.2700, 554: -0.3463, chf: 0.2843, none: 0.4273

column_table_A: Franc Congolais | Euro | Australian Dollar | New Zealand Dollar | Chilean Peso
column_table_B: Campione d'Italia, Liechtenstein, Switzerland | Czech Republic | Chile | Hospitaller Malta, Hospitaller Rhodes, Crown Colony of Malta, French occupation of Malta, Gozo (independent state), Malta Protectorate, Sovereign Military Order of Malta | Cambodia
token_weights: franc: -0.0706, euro: -0.0440, dollar: -0.0515, new: 0.3506, zealand: -0.0507, dollar: -0.0515, peso: -0.0706, liechtenstein: 0.1933, switzerland: -0.1045, republic: -0.0464, chile: -0.3666, crown: 0.0848, colony: -0.0869, of: -0.4651, french: -0.0209, of: -0.4651, state: -0.1767, sovereign: -0.0098, of: -0.4651

column_table_A: Congo, The Democratic Republic Of | French Southern Territories | Cocos (Keeling) Islands | Cook Islands | Chile
column_table_B: Campione d'Italia, Liechtenstein, Switzerland | Czech Republic | Chile | Hospitaller Malta, Hospitaller Rhodes, Crown Colony of Malta, French occupation of Malta, Gozo (independent state), Malta Protectorate, Sovereign Military Order of Malta | Cambodia
token_weights: the: -0.3987, republic: -0.0464, of: -0.4651, french: -0.0209, southern: 0.1342, cocos: -0.0532, keeling: -0.1678, islands: -0.1989, cook: 0.0286, islands: -0.1989, chile: -0.3666, liechtenstein: 0.1933, switzerland: -0.1045, republic: -0.0464, chile: -0.3666, crown: 0.0848, colony: -0.0869, of: -0.4651, french: -0.0209, of: -0.4651, state: -0.1767, sovereign: -0.0098, of: -0.4651

column_table_A: nan |  | A$ | NZ$ | Ch$
column_table_B: Campione d'Italia, Liechtenstein, Switzerland | Czech Republic | Chile | Hospitaller Malta, Hospitaller Rhodes, Crown Colony of Malta, French occupation of Malta, Gozo (independent state), Malta Protectorate, Sovereign Military Order of Malta | Cambodia
token_weights: nan: 0.1721, liechtenstein: 0.1933, switzerland: -0.1045, republic: -0.0464, chile: -0.3666, crown: 0.0848, colony: -0.0869, of: -0.4651, french: -0.0209, of: -0.4651, state: -0.1767, sovereign: -0.0098, of: -0.4651

column_table_A: Franc Congolais | Euro | Australian Dollar | New Zealand Dollar | Chilean Peso
column_table_B: nan | haléřa | nan | Tarì, piccolo, grano | kak, sen
token_weights: franc: -0.0706, euro: -0.0440, dollar: -0.0515, new: 0.3506, zealand: -0.0507, dollar: -0.0515, peso: -0.0706, nan: 0.1721, nan: 0.1721, sen: 0.1713

column_table_A: CDF | EUR | AUD | NZD | CLP
column_table_B: nan | haléřa | nan | Tarì, piccolo, grano | kak, sen
token_weights: eur: 0.2259, nan: 0.1721, nan: 0.1721, sen: 0.1713

column_table_A: 100 centimes | 100 euro-cents | 100 cents | 100 cents | 100 centavos
column_table_B: nan | haléřa | nan | Tarì, piccolo, grano | kak, sen
token_weights: 100: -0.0244, centimes: 0.1231, 100: -0.0244, euro: -0.0440, cents: -0.0713, 100: -0.0244, cents: -0.0713, 100: -0.0244, cents: -0.0713, 100: -0.0244, nan: 0.1721, nan: 0.1721, sen: 0.1713

column_table_A: 976 | 978 | 36 | 554 | 152
column_table_B: nan | haléřa | nan | Tarì, piccolo, grano | kak, sen
token_weights: 978: -0.3476, 36: -0.2700, 554: -0.3463, nan: 0.1721, nan: 0.1721, sen: 0.1713

column_table_A: Congo, The Democratic Republic Of | French Southern Territories | Cocos (Keeling) Islands | Cook Islands | Chile
column_table_B: , Campione d'Italia, Italy | nan | nan | Crown Colony of Malta, Sovereign Military Order of Malta, Hospitaller Malta, Previously:, Malta Protectorate, Hospitaller Rhodes, French Malta, Independent Gozo | nan
token_weights: the: -0.3987, republic: -0.0464, of: -0.4651, french: -0.0209, southern: 0.1342, cocos: -0.0532, keeling: -0.1678, islands: -0.1989, cook: 0.0286, islands: -0.1989, chile: -0.3666, italy: -0.0268, nan: 0.1721, nan: 0.1721, crown: 0.0848, colony: -0.0869, of: -0.4651, sovereign: -0.0098, of: -0.4651, french: -0.0209, nan: 0.1721

column_table_A: CDF | EUR | AUD | NZD | CLP
column_table_B: , Campione d'Italia, Italy | nan | nan | Crown Colony of Malta, Sovereign Military Order of Malta, Hospitaller Malta, Previously:, Malta Protectorate, Hospitaller Rhodes, French Malta, Independent Gozo | nan
token_weights: eur: 0.2259, italy: -0.0268, nan: 0.1721, nan: 0.1721, crown: 0.0848, colony: -0.0869, of: -0.4651, sovereign: -0.0098, of: -0.4651, french: -0.0209, nan: 0.1721

column_table_A: 100 centimes | 100 euro-cents | 100 cents | 100 cents | 100 centavos
column_table_B: , Campione d'Italia, Italy | nan | nan | Crown Colony of Malta, Sovereign Military Order of Malta, Hospitaller Malta, Previously:, Malta Protectorate, Hospitaller Rhodes, French Malta, Independent Gozo | nan
token_weights: 100: -0.0244, centimes: 0.1231, 100: -0.0244, euro: -0.0440, cents: -0.0713, 100: -0.0244, cents: -0.0713, 100: -0.0244, cents: -0.0713, 100: -0.0244, italy: -0.0268, nan: 0.1721, nan: 0.1721, crown: 0.0848, colony: -0.0869, of: -0.4651, sovereign: -0.0098, of: -0.4651, french: -0.0209, nan: 0.1721

column_table_A: nan |  | A$ | NZ$ | Ch$
column_table_B: , Campione d'Italia, Italy | nan | nan | Crown Colony of Malta, Sovereign Military Order of Malta, Hospitaller Malta, Previously:, Malta Protectorate, Hospitaller Rhodes, French Malta, Independent Gozo | nan
token_weights: nan: 0.1721, italy: -0.0268, nan: 0.1721, nan: 0.1721, crown: 0.0848, colony: -0.0869, of: -0.4651, sovereign: -0.0098, of: -0.4651, french: -0.0209, nan: 0.1721

column_table_A: BP | Toyota | Allianz | ExxonMobil | JPMorgan Chase & Co.
column_table_B: Mallinckrodt | PulteGroup | Crown Holdings | EOG Resources | Denbury Resources
token_weights: bp: -0.0806, exxonmobil: -0.0044, jpmorgan: -0.0220, chase: -0.0558, co: 0.0483, crown: 0.0848, holdings: 0.0848, resources: -0.1209, resources: -0.1209

column_table_A: UK | Japan | Germany | USA | USA
column_table_B: Mallinckrodt | PulteGroup | Crown Holdings | EOG Resources | Denbury Resources
token_weights: uk: -0.1700, japan: 0.1960, germany: -0.1077, usa: 0.8833, usa: 0.8833, crown: 0.0848, holdings: 0.0848, resources: -0.1209, resources: -0.1209

column_table_A: 265.91 | 179.02 | 125.33 | 335.09 | 99.3
column_table_B: Mallinckrodt | PulteGroup | Crown Holdings | EOG Resources | Denbury Resources
token_weights: 91: 0.0983, 179: -0.2777, 02: 0.1948, 125: -0.2461, 33: -0.0113, 09: 0.0963, 99: 0.2298, crown: 0.0848, holdings: 0.0848, resources: -0.1209, resources: -0.1209

column_table_A: 11 | 12 | 15 | 7 | 5
column_table_B: Mallinckrodt | PulteGroup | Crown Holdings | EOG Resources | Denbury Resources
token_weights: 11: -0.0889, 12: 0.1170, 15: 0.2513, crown: 0.0848, holdings: 0.0848, resources: -0.1209, resources: -0.1209

column_table_A: 22.29 | 11.68 | 8.81 | 39.5 | 14.44
column_table_B: Mallinckrodt | PulteGroup | Crown Holdings | EOG Resources | Denbury Resources
token_weights: 22: -0.2578, 29: -0.1883, 11: -0.0889, 68: -0.2704, 81: -0.3303, 39: 0.4615, 14: 0.0349, 44: -0.0306, crown: 0.0848, holdings: 0.0848, resources: -0.1209, resources: -0.1209

column_table_A: BP | Toyota | Allianz | ExxonMobil | JPMorgan Chase & Co.
column_table_B: MNKKQ | PHM | CCK | EOG | DEN
token_weights: bp: -0.0806, exxonmobil: -0.0044, jpmorgan: -0.0220, chase: -0.0558, co: 0.0483,

column_table_A: 217.60 | 243.60 | 1,380.88 | 223.95 | 1,351.52
column_table_B: MNKKQ | PHM | CCK | EOG | DEN
token_weights: 217: 0.0072, 60: -0.0518, 243: -0.1886, 60: -0.0518, 88: 0.0350, 95: -0.0244, 351: -0.1020, 52: -0.4112,

column_table_A: BP | Toyota | Allianz | ExxonMobil | JPMorgan Chase & Co.
column_table_B: nan | CEO, CFO, Executive Vice-President | CEO, CFO | CEO, CFO | President (corporate title), CFO
token_weights: bp: -0.0806, exxonmobil: -0.0044, jpmorgan: -0.0220, chase: -0.0558, co: 0.0483, nan: 0.1721, ceo: -0.0868, cfo: -0.0868, executive: -0.0868, vice: -0.1904, president: -0.2145, ceo: -0.0868, cfo: -0.0868, ceo: -0.0868, cfo: -0.0868, president: -0.2145, cfo: -0.0868

column_table_A: Oil and gas | Automotive | Insurance | Oil and gas | Banking

In [57]:
print(df_test.head())

   table_index                      table_name  column_index_left  \
0            0  29021592_3_2299138476894681059                  0
1            1  29021592_3_2299138476894681059                  3
2            2  29021592_3_2299138476894681059                  4
3            3  29021592_3_2299138476894681059                  2
4            4  29021592_3_2299138476894681059                  0

   column_index_right  y_true  y_pred  \
0                   0       1       0
1                   0       0       0
2                   0       0       0
3                   0       0       0
4                   3       0       0

                                      column_table_A  \
0        Domitian | Nerva | Hadrian | Trajan | Titus
1  Titus Flavius Domitianus | Marcus Cocceius Ner...
2              81-96 | 96-8 | 117-8 | 98-117 | 79-81
3                        nan | nan | nan | nan | nan
4        Domitian | Nerva | Hadrian | Trajan | Titus

                                      column_table_B  \
0  Trajan | Titus | Marcus Silius Messala | Vespa...
1  Trajan | Titus | Marcus Silius Messala | Vespa...
2  Trajan | Titus | Marcus Silius Messala | Vespa...
3  Trajan | Titus | Marcus Silius Messala | Vespa...
4  Imperator Caesar Nerva Traianus Augustus | Imp...

                                             table_A  \
0  | Column A-0   | Column A-1        |   Column ...
1  | Column A-0   | Column A-1        |   Column ...
2  | Column A-0   | Column A-1        |   Column ...
3  | Column A-0   | Column A-1        |   Column ...
4  | Column A-0   | Column A-1        |   Column ...

                                             table_B  \
0  | Column B-0            |   Column B-1 | Colum...
1  | Column B-0            |   Column B-1 | Colum...
2  | Column B-0            |   Column B-1 | Colum...
3  | Column B-0            |   Column B-1 | Colum...
4  | Column B-0            |   Column B-1 | Colum...

                                     tables_combined  \
0  | Column A-0   | Column A-1        |   Column ...
1  | Column A-0   | Column A-1        |   Column ...
2  | Column A-0   | Column A-1        |   Column ...
3  | Column A-0   | Column A-1        |   Column ...
4  | Column A-0   | Column A-1        |   Column ...

                                       token_weights
0                                                 ,
1                                                 ,
2  81: -0.3303, 96: -0.5253, 96: -0.5253, 117: 0....
3  nan: 0.1721, nan: 0.1721, nan: 0.1721, nan: 0....
4  , caesar: -0.0357, caesar: -0.0357, nan: 0.172...

In [ ]:
df_test.to_csv(OUTPUT_PATH, index=False)